[package]
name = "measureme"
version = "0.1.0"
authors = ["Wesley Wiser <wwiser@gmail.com>", "Michael Woerister <michaelwoerister@posteo>"]
edition = "2018"
description = "Support crate for rustc's self-profiling feature"
license = "MIT OR Apache-2.0"

[badges]
travis-ci = { repository = "rust-lang/measureme" }

[dependencies]
byteorder = "1.3"
rustc-hash = "1.0.1"
memmap = "0.7.0"
