[package]
name = "mmview"
version = "0.6.0"
authors = ["Wesley Wiser <wwiser@gmail.com>", "Michael Woerister <michaelwoerister@posteo>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
analyzeme = { path = "../analyzeme" }
measureme = { path = "../measureme" }
structopt = "0.2"
