[package]
name = "mmedit"
version = "10.1.2"
edition = "2018"

[dependencies]
measureme = { path = "../measureme" }
decodeme = { path = "../decodeme" }
clap = { version = "3.2", features = ["derive"] }
